@startuml
<style>
activityDiagram {
  BackgroundColor #FAFAFA
  BorderColor #CCCCCC
  FontColor #333
  FontName Segoe UI

  diamond {
    BackgroundColor #E0F0FF
    LineColor #007ACC
    FontColor #003366
    FontName Segoe UI
    FontSize 14
  }

  arrow {
    FontColor #333
    FontName Segoe UI
    FontSize 13
    LineColor #555
  }

  partition {
    LineColor #007ACC
    FontColor #004466
    BackgroundColor #F5F9FC
    RoundCorner 12
  }

  note {
    FontColor #004466
    LineColor #007ACC
    BackgroundColor #F0F8FF
    FontName Segoe UI
  }
}

document {
   BackgroundColor white
}
</style>


title Proceso PR-AS-01: Afiliaciones, Novedades, Movilidades y Traslados



start

partition "Línea de Frente / Personal de Ventanilla" {
  :INICIO;
  :1. Recepción de la solicitud inicial;
  :2. Validación del tipo de solicitante;
  :3. Validación de información actual;
  :4. Validación de anexos;
  if (5. ¿Cumple con los requisitos del trámite?) then (NO)
    :Informar al usuario o solicitante sobre los motivos normativos o falta de soportes. Detallar proceso alternativo o corrección necesaria.;
    stop
  else (SÍ)
    :6. Cargar la solicitud al sistema;
    :7. Confirmación y entrega de información;
  endif
}

partition "Sistema de la EPS" {
  :8. Asignación de red de servicios;
}

partition "Profesional de Aseguramiento / Analista BDUA" {
  :9. Descarga archivos .txt del reporte SIE de la EPS;
  note left
  Retorna a este punto luego de dar 
  respuesta a todas las solicitudes de 
  traslado de salida punto 22.
  end note
  :10. Validación de la veracidad de los registros a reportar;
  :11. Validación de estructura de los reportes;

  while (12. ¿Se genera el Pak?) is (No)
    :13. Corregir glosas de estructura;
  endwhile (Sí)

  :14. Cargue del proceso ante ADRES;
}

partition "Técnico de apoyo" {
  :15. Cargue del oficio en formato PDF ante ADRES;
}

partition "Profesional de Aseguramiento / Analista BDUA" {
  :16. Descargar Archivos del sitio FTP;

  if (17. ¿Se cargan MS, MC, NS y NC validados y negados ADRES?) then (Sí)
  'space label only for alignment
    label sp_lab5
    label sp_lab4
    label sp_lab3
    label sp_lab2
    label sp_lab1
    'real label
    label lab
  :23. Corrección de glosas;
  else (No)
        if (18. ¿Se cargan S4 y R4 validados y negados ADRES, S5 y R5?) then (Sí)
            label sp_lab2
            goto sp_lab1
            else (No)
                if (19. ¿Se cargan S1.VAL, AUTOMATICO-S1, S3, R1.VAL, AUTOMATICO-R1, y R3 respuestas ADRES?) then (Sí)
                label sp_lab2
                goto sp_lab1
                else (No)
                if (20. ¿Se cargan S2 y R2 ADRES?) then (No)
                    label sp_lab2
                    goto sp_lab1
                    else (sí)
                    repeat
                      :21. Dar respuesta solicitudes de traslado de salida **(Técnico de apoyo)**;
                    repeat while (22. ¿Se gestionaron todas las solicitudes de traslado de salida?)
                        :Retomar proceso de validación desde paso 9.;
                        stop
                    
                endif
            endif
        endif
        
endif
}




partition "Línea de Frente / Personal de Ventanilla" {
  :24. Envío alcaldía;
  :25. Emisión de certificado de afiliación CAPRESOCA EPS;
}

partition "Profesional de Aseguramiento / Analista BDUA" {
  :26. Cierre del proceso: archivo y medición de indicadores;
}

stop
@enduml
